// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import repository "testProject/learning/example/api_jwt_mongo/repository"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// GetUserRI provides a mock function with given fields:
func (_m *Storage) GetUserRI() repository.UserRepo {
	ret := _m.Called()

	var r0 repository.UserRepo
	if rf, ok := ret.Get(0).(func() repository.UserRepo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepo)
		}
	}

	return r0
}

// Init provides a mock function with given fields: uri
func (_m *Storage) Init(uri string) {
	_m.Called(uri)
}

// SetDB provides a mock function with given fields: name
func (_m *Storage) SetDB(name string) {
	_m.Called(name)
}
